services:
  mx-space:
    container_name: ${CONTAINER_NAME}
    image: innei/mx-server:latest
    command: bash ./docker-run.sh
    environment:
      - TZ=${TIME_ZONE}
      - NODE_ENV=production
      - DB_COLLECTION_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}/${REDIS_DB_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - ENCRYPT_ENABLE=${ENCRYPT_ENABLE}
    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '${PANEL_APP_PORT_HTTP}:2333'
    networks:
      - 1panel-network
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:  
      createdBy: "Apps" 

networks:  
  1panel-network:  
    external: true
